apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}        
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KAFKA_BROKERCONNECT
            value: "{{ .Values.kafka.brokerConnect }}"
          - name: KAFKA_PROPERTIES_FILE
            value: "kafka.properties"
          - name: JVM_OPTS
            value: "{{ .Values.jvm.opts }}"
          - name: JMX_PORT
            value: "{{ .Values.jmx.port }}"
          {{- if .Values.host }}
          - name: HOST
            value: "{{ .Values.host }}"
          {{- end }}
          - name: SERVER_SERVLET_CONTEXTPATH
            value: "{{ .Values.server.servlet.contextPath | trimSuffix "/" }}"
          - name: SERVER_PORT
            value: "{{ .Values.server.port }}"
          command: ["/bin/sh", "-c"]
          args:
          - cp /etc/kafka/config/kafka.properties .;
            {{- if hasKey .Values.kafka.properties "ssl.key.credentials" }}
            echo ssl.key.password=`cat {{index .Values "kafka" "properties" "ssl.key.credentials"}}` >> kafka.properties;
            {{- end }}
            {{- if hasKey .Values.kafka.properties "ssl.keystore.credentials" }}
            echo ssl.keystore.password=`cat {{index .Values "kafka" "properties" "ssl.keystore.credentials"}}` >> kafka.properties;
            {{- end }}
            {{- if hasKey .Values.kafka.properties "ssl.truststore.credentials" }}
            echo ssl.truststore.password=`cat {{index .Values "kafka" "properties" "ssl.truststore.credentials"}}` >> kafka.properties;
            {{- end }}
            java --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Xss256K $JVM_OPTS -jar /kafdrop*/kafdrop*jar
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.server.servlet.contextPath | trimSuffix "/" }}/actuator/health"
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: "{{ .Values.server.servlet.contextPath | trimSuffix "/" }}/actuator/health"
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/kafka/config
            readOnly: true
{{- if .Values.kafka.secret }}
          - name: secret-volume
            mountPath: /etc/kafka/secrets
            readOnly: true
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "chart.fullname" . }}
{{- if .Values.kafka.secret }}
      - name: secret-volume
        secret:
          secretName: {{ .Values.kafka.secret }}
{{- end }}